### ISSUE TITLE
Issues on a fresh clone

### ISSUE THREAD

**Issue by omidn** [SmartDataAnalytics/HORUS-NER#39]
I tried to clone the repository and I have some problems getting it up and running.

Initially, I had the `horus_dist.ini` to `~/horus.ini` copied and set the parameters. 

Next, I tried to install the module with: 
`python setup.py install --record files.txt`
And it failed with the following error message:
`error: package directory 'src/horus/sift' does not exist`

The next thing I tried was to run the source code directly without having the whole module installed. I had two issues:

1. The `horus.ini` file that I copied from the `src/horus/resource/horus_dist.init` has some missing keys. I just added added an empty key for those keys but I'm not sure if that's going to resolve all the issues or not. 

2. I did not had the database in advance. I tried to create the database with `./src/horus/components/util/script_db.py`. The db model in this file is obsolete. I tried to run  `./src/horus/components/webservice/rest.py` and the model needed a some columns that did not exist in my database.

**Comment by diegoesteves** [comment]
The new release will fix those issues w/ `pipenv`
